### ISSUE TITLE
All workers die even with spawn-interval

### ISSUE THREAD

**Issue by limitusus** [kazuho/Starlet#27]
@kazuho 

From @d20fdcb88aba0dacc902a97e6fe3a6fc3a2e8fc1 and later (thus v0.28), plack with `--spawn-interval` dies several seconds after receiving SIGHUP with `start_server`.

I have not made a test nor fix code but I bisected by hand and found the cause commit is it.

Here is repoduce procedure:

app.psgi (whatever)
```perl
my $app = sub {
    return [200, [], ["hello"]];
};
```

Launch plack workers under Starlet and start_server
```bash
PERL5OPT="-I./Starlet/lib/" carton exec start_server --port=9000 --signal-on-hup=USR1 -- plackup -s Starlet ~/app.psgi  --spawn-interval=1
```
and wait for 10 seconds to all workers spawn.

```bash
kill -HUP $server_starter_pid
```
and checked `kill -HUP $server_starter_pid` in a short interval.

Before this commit the old generation workers die one by one per second.
With this commit, I could observe only one worker died and then all others died simultaneously.

I think this commit did not considered about late-dying worker and plack master process sent SIGTERM too all other workers.

**Comment by limitusus** [comment]
I think such patch and test will be enough: https://github.com/kazuho/Starlet/compare/master...limitusus:hotfix/spawn-interval?expand=1

**Comment by kazuho** [comment]
Thank you for reporting the issue.  The proposed code looks generally fine to me.  Let's work in #28 to get it merged.

**Comment by limitusus** [comment]
I should close this issue as #28 completed.

**Comment by kazuho** [comment]
Thank you for your contribution!
